- name: Debian conf
  hosts: all
  remote_user: vagrant
  sudo: yes

  roles:
    - debian

- name: Install emqtt
  hosts: all
  remote_user: vagrant
  sudo: no

  roles:
    - emqttd

- name: Install xbmc
  hosts: all
  remote_user: vagrant
  sudo: yes

  roles:
    - xbmc
