- name: Debian conf
  hosts: all
  remote_user: "{{ remote_user }}"
  sudo: yes

  roles:
    - debian

- name: Install emqtt
  hosts: all
  remote_user: "{{ remote_user }}"
  sudo: no

  roles:
    - emqttd

- name: Install mosquitto
  hosts: all
  remote_user: "{{ remote_user }}"
  sudo: yes

  roles:
    - mosquitto

- name: Install xbmc
  hosts: all
  remote_user: "{{ remote_user }}"
  sudo: yes

  roles:
    - xbmc
