---
  - name: Download emqtt
    get_url: >
      dest=/opt/
      url="http://emqtt.io/downloads/ubuntu"

  - name: Unzip emqtt
    command: unzip /opt/emqttd-ubuntu64-0.13.0-beta-20151108.zip

  - name: Install emqttd daemon
    copy: >
      src="../etc/init.d/emqttd"
      dest="/etc/init.d/"
      mode="-rwxr-xr-x"

  - name: Add to daemon list
    command: chkconfig --add emqttd

  - name: Start emqttd daemon
    service: >
      name=emqttd
      enabled=yes
